### ISSUE TITLE
Fases de la gestión de proyectos de software

### ISSUE THREAD

**Issue by IvanMc98** [SistemasTecTlaxiaco/infografia-IvanMc98-1#2]
[Gestion de sotware - infografia.pdf](https://github.com/SistemasTecTlaxiaco/infografia-IvanMc98-1/files/7145672/Gestion.de.sotware.-.infografia.pdf)

**Comment by EDITH-R** [comment]
Calificación:20

**Comment by josealfredo79** [comment]
Faltan las metodologías las herramientas...

**Comment by josealfredo79** [comment]
Checar bien...para la proxima no se acepta el trabajo...
